### ISSUE TITLE
Allow <listRelation> in teiHeader

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-schema#13]
Now that we added character relations (see https://github.com/dracor-org/gerdracor/commit/1095d70934ab525f866a2f1978541eeedf618651), please allow listRelation in our schema.

**Comment by ingoboerner** [comment]
http://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.html

**Comment by lehkost** [comment]
What we do with listRelations is documented here:
https://github.com/quadrama/Corpus#relations
Is that enough for the time being?
