### ISSUE TITLE
Allowing a <back> element?

### ISSUE THREAD

**Issue by pruizf** [dracor-org/dracor-schema#17]
I'm working on encoding _Chrischtowe_ by Paul Clements, which is meant to be part of Alsdracor. We now have a valid TEI version (against TEI-all), however, to make it DraCor valid, I wonder if the DraCor schema could consider some additions.

The first one is allowing a `<back>` element. That way the last paragraph in the play could be encoded as a `<back>`, see the source page in the play: https://www.numistral.fr/ark:/12148/bpt6k91095403/f25.image.r=chrischtowe

If `<back>` cannot be added, I wonder what your preferred way of encoding information like that would be (it's credits for a poem that's reproduced in the play).

**Comment by lehkost** [comment]
Sorry for the late reply. This two-liner could go as ```<stage>``` direction for the time being (we did so in similar cases in GerDraCor).

**Comment by ingoboerner** [comment]
I would consider this a `<byline>` see https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-byline.html which could simply go after the last `<stage>`

**Comment by lehkost** [comment]
@pruizf, would that work for you?

**Comment by pruizf** [comment]
Hello! Thanks for the answer. I think it could be made to work with `<byline>`. But the author identified on that paragraph is not the author of the entire play, that paragraph is there to give credit to an author whose poem was reproduced in the play (starts here: https://www.numistral.fr/ark:/12148/bpt6k91095403/f23.item.r=chrischtowe). So the `<byline>` would need to refer back to the element containing the poem (with a `@corresp`?). I would be happy to work that way for now and if I do find cases that would require a `<back>` I let you know?
