### ISSUE TITLE
xml:id on tei:TEI?

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-schema#2]
use dracorID as xml:id on the root element of each play?

**Comment by cmil** [comment]
@ingoboerner I think we did :)

**Comment by lehkost** [comment]
Even if not on tei:TEI, we now have global IDs and a corresponding resolver (see dracor-org/dracor-api#32).
@ingoboerner: Can we close this issue or would you still opt for an xml:id on tei:TEI?

**Comment by lb42** [comment]
I strongly prefer using TEI/@xml:id for this purpose... but you don't have to make it mandatory

**Comment by cmil** [comment]
The DraCor API v1 dropped support for extracting the DraCor ID of a play from an `idno` element leaving `TEI/@xml:id` as the only way to specify it. So should we make `TEI/@xml:id` mandatory now or keep it optional to support work-in-progress kind of scenarios?

**Comment by cmil** [comment]
> The DraCor API v1 dropped support for extracting the DraCor ID of a play from an `idno` element leaving `TEI/@xml:id` as the only way to specify it. So should we make `TEI/@xml:id` mandatory now or keep it optional to support work-in-progress kind of scenarios?

`TEI/@xml:id` is currently mandatory:

https://github.com/dracor-org/dracor-schema/blob/01284fabc9aa45dfb712456592a3b3293ea9cf22/dracor.odd#L5015-L5015

So should we follow @lb42's suggestion and make it optional, @lehkost, @ingoboerner?

**Comment by lb42** [comment]
That rather depends on how the api behaves in the absence of any unique dracor id!

**Comment by cmil** [comment]
@lb42 The API kind of expects the `TEI/@xml:id` but does not enforce it. I would lean towards keeping it mandatory unless there are use cases omitting it. In which case I'd suggest to deal with it in a new issue.

**Comment by lb42** [comment]
Makes sense to me!
