### ISSUE TITLE
Validation Problems in GerDraCor

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-schema#23]
There are some issues when validating all GerDraCor-Files, but probably not everything should go into the schema 
@lehkost could you pls validate all files and identify additional necessary changes to the schema?

**Comment by lehkost** [comment]
Please add ```<div type="review">``` (used in https://dracor.org/id/ger000212#text).

**Comment by ingoboerner** [comment]
validation of gerdracor at https://github.com/dracor-org/gerdracor/commit/42b60c0f0aa2b7181c0b8bae7e637ff44c9a0a07 should validate w/o errors
