### ISSUE TITLE
Unify genre declaration

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-schema#3]
GerDraCor and RusDraCor currently use different ways to declare the genre of a play.

GerDraCor: `<term type="genreTitle">Schauspiel</term>`
RusDraCor: `<term type="genreTitle" subtype="comedy">Комедия в пяти действиях</term>`

(see also https://github.com/dracor-org/dracor-exist/issues/14#issuecomment-386920386)

**Comment by lehkost** [comment]
Suggestion by @dariok:
```xml
<textClass>
  <keywords scheme="https://d-nb.info/gnd">
    <term>Tragedy</term>
  </keywords>
  <classCode scheme="https://www.wikidata.org/entity/">Q80930</classCode>
</textClass>
```
Uses WIkidata as external reference taxonomy, [Q80930](https://www.wikidata.org/wiki/Q80930) would be "tragedy".
We can also identify libretti by adding:
```xml
<classCode scheme="https://www.wikidata.org/entity/">Q131084</classCode>
```

**Comment by lehkost** [comment]
For the time being, we decided to go with very broad genre declarations on two levels:
### comedy or tragedy:
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Comedy</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q40831</classCode>
</textClass>
```
or
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Tragedy</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q80930</classCode>
</textClass>
```
### libretto or not:
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Libretto</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q131084</classCode>
</textClass>
```
We already marked-up some plays in GerDraCor as showcase (see https://github.com/dracor-org/gerdracor/commit/98b713bebbd47d8b024c07db62eafe0150a856a1) for implementing a genre extraction feature in the API (as part of the metadata of plays).
