### ISSUE TITLE
<hi> vs. <emph>

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-schema#4]
@lehkost @mathias-goebel Shall we allow `<hi>` in schema, e.g.
``
 <sp who="#schoen">
            <speaker>SCHÖN</speaker>
            <stage>
              <hi>kniet neben einem Blumenbeete.</hi>
            </stage>
            <p>'n Bast!</p>
            <stage>
              <hi>Anna begießt ein Beet, eine zweite Gießkanne steht neben ihr.</hi>
            </stage>
</sp>
``

**Comment by lehkost** [comment]
Not right now. We're trying to clear out all ```<hi>``` from GerDraCor and convert them to either ```<stage>``` or ```<emph>```. In RusDraCor, we constantly use ```<emph>```.

**Comment by lehkost** [comment]
This has been solved for GerDraCor with the finalisation of the correction cycle in May 2019. No more ```<hi>``` in GerDraCor (and RusDraCor).
