### ISSUE TITLE
obsolete <anchor>s,<ptr>s, <ref> 

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-schema#7]
There are some empty `<anchor>`,`<ptr>`, `<ref>` elements in the data. They are probably used to anchor notes. Shall we include them in the schema?

``<p>Damit es nun in der Zwischenzeit, bis sich wieder ein ähnlicher Thor von Bühnenleiter zu
          seiner Annahme bereit findet, nicht altbacken werde,<ref><anchor/><ptr/><hi>1</hi></ref>
          übergebe ich es hiermit der Oeffentlichkeit, nachdem die ersten dramaturgischen
          Autoritäten Deutschlands, denen es vorgelegen, ihm das allerfreundlichste Geleit mit auf
          den Weg gegeben.</p>``

**Comment by lehkost** [comment]
Nope, don't include them, they have all been dissolved to ```<note place="foot">``` in the meantime.
