### ISSUE TITLE
Harmonize usage of xml:lang on root Element?

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-schema#9]
RusDraCor puts `@xml:lang` on the root `<TEI>`, GerDraCor doesn't. Shall we make it mandatory or notate the language of the drama elsewhere?

**Comment by ingoboerner** [comment]
Values should come from ISO-639-2 (B)
https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by lehkost** [comment]
This is now done for the following DraCor corpora:
* als
* ger
* greek
* rom
* rus
* tat

The other corpora don't apply a language for the TEI root element yet:
* cal
* shake
* span
* swe
